name: CI Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential pkg-config
        sudo apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev libglew-dev
        sudo apt-get install -y xvfb # For headless testing
    
    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git --depth 1
        ./vcpkg/bootstrap-vcpkg.sh
        echo "VCPKG_ROOT=$PWD/vcpkg" >> $GITHUB_ENV
    
    - name: Cache vcpkg packages
      uses: actions/cache@v3
      with:
        path: ${{ env.VCPKG_ROOT }}/installed
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-
    
    - name: Configure CMake
      run: |
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake \
          -DVCPKG_TARGET_TRIPLET=x64-linux
    
    - name: Build Application
      run: cmake --build build --config Release --target sdl_app
    
    - name: Build Tests
      run: cmake --build build --target sdl_appTests
    
    - name: Run Tests
      run: |
        cd build
        xvfb-run -a ./sdl_appTests --reporter=junit --out=../test-results.xml
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: test-results.xml
        check_name: "Matrix4 Unit Tests"
        comment_title: "🧮 Matrix4 Unit Test Results"
        
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: |
          test-results.xml
          build/sdl_appTests
